language: go
arch:
  - amd64
  - arm64

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make
  - docker build . -t $DOCKER_USERNAME/container_restarter:$(go env GOHOSTARCH)
  - docker push $DOCKER_USERNAME/container_restarter:$(go env GOHOSTARCH)
